// Code generated by go-swagger; DO NOT EDIT.

package sample_description

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewShowGreetingsToTheAPIParams creates a new ShowGreetingsToTheAPIParams object
// no default values defined in spec.
func NewShowGreetingsToTheAPIParams() ShowGreetingsToTheAPIParams {

	return ShowGreetingsToTheAPIParams{}
}

// ShowGreetingsToTheAPIParams contains all the bound params for the show greetings to the api operation
// typically these are obtained from a http.Request
//
// swagger:parameters Show greetings to the api
type ShowGreetingsToTheAPIParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewShowGreetingsToTheAPIParams() beforehand.
func (o *ShowGreetingsToTheAPIParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
