// Code generated by go-swagger; DO NOT EDIT.

package sample_description

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ShowGreetingsToTheAPIOKCode is the HTTP code returned for type ShowGreetingsToTheAPIOK
const ShowGreetingsToTheAPIOKCode int = 200

/*ShowGreetingsToTheAPIOK returns greetings to the API

swagger:response showGreetingsToTheApiOK
*/
type ShowGreetingsToTheAPIOK struct {

	/*consumes actual greetings
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewShowGreetingsToTheAPIOK creates ShowGreetingsToTheAPIOK with default headers values
func NewShowGreetingsToTheAPIOK() *ShowGreetingsToTheAPIOK {

	return &ShowGreetingsToTheAPIOK{}
}

// WithPayload adds the payload to the show greetings to the Api o k response
func (o *ShowGreetingsToTheAPIOK) WithPayload(payload string) *ShowGreetingsToTheAPIOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show greetings to the Api o k response
func (o *ShowGreetingsToTheAPIOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowGreetingsToTheAPIOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
