// Code generated by go-swagger; DO NOT EDIT.

package foods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteFoodHandlerFunc turns a function with the right signature into a delete food handler
type DeleteFoodHandlerFunc func(DeleteFoodParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFoodHandlerFunc) Handle(params DeleteFoodParams) middleware.Responder {
	return fn(params)
}

// DeleteFoodHandler interface for that can handle valid delete food params
type DeleteFoodHandler interface {
	Handle(DeleteFoodParams) middleware.Responder
}

// NewDeleteFood creates a new http.Handler for the delete food operation
func NewDeleteFood(ctx *middleware.Context, handler DeleteFoodHandler) *DeleteFood {
	return &DeleteFood{Context: ctx, Handler: handler}
}

/*DeleteFood swagger:route DELETE /food/{food_id} foods deleteFood

DeleteFood delete food API

*/
type DeleteFood struct {
	Context *middleware.Context
	Handler DeleteFoodHandler
}

func (o *DeleteFood) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteFoodParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
