// Code generated by go-swagger; DO NOT EDIT.

package foods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFoodNoContentCode is the HTTP code returned for type DeleteFoodNoContent
const DeleteFoodNoContentCode int = 204

/*DeleteFoodNoContent delete a food

swagger:response deleteFoodNoContent
*/
type DeleteFoodNoContent struct {
}

// NewDeleteFoodNoContent creates DeleteFoodNoContent with default headers values
func NewDeleteFoodNoContent() *DeleteFoodNoContent {

	return &DeleteFoodNoContent{}
}

// WriteResponse to the client
func (o *DeleteFoodNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
