// Code generated by go-swagger; DO NOT EDIT.

package foods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFoodsHandlerFunc turns a function with the right signature into a get foods handler
type GetFoodsHandlerFunc func(GetFoodsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFoodsHandlerFunc) Handle(params GetFoodsParams) middleware.Responder {
	return fn(params)
}

// GetFoodsHandler interface for that can handle valid get foods params
type GetFoodsHandler interface {
	Handle(GetFoodsParams) middleware.Responder
}

// NewGetFoods creates a new http.Handler for the get foods operation
func NewGetFoods(ctx *middleware.Context, handler GetFoodsHandler) *GetFoods {
	return &GetFoods{Context: ctx, Handler: handler}
}

/*GetFoods swagger:route GET /food foods getFoods

GetFoods get foods API

*/
type GetFoods struct {
	Context *middleware.Context
	Handler GetFoodsHandler
}

func (o *GetFoods) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFoodsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
