// Code generated by go-swagger; DO NOT EDIT.

package foods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"food_app/food_app/models"
)

// GetFoodsOKCode is the HTTP code returned for type GetFoodsOK
const GetFoodsOKCode int = 200

/*GetFoodsOK list all foods

swagger:response getFoodsOK
*/
type GetFoodsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Food `json:"body,omitempty"`
}

// NewGetFoodsOK creates GetFoodsOK with default headers values
func NewGetFoodsOK() *GetFoodsOK {

	return &GetFoodsOK{}
}

// WithPayload adds the payload to the get foods o k response
func (o *GetFoodsOK) WithPayload(payload []*models.Food) *GetFoodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get foods o k response
func (o *GetFoodsOK) SetPayload(payload []*models.Food) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFoodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Food, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
