// Code generated by go-swagger; DO NOT EDIT.

package foods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"food_app/food_app/models"
)

// NewUpdateFoodParams creates a new UpdateFoodParams object
// no default values defined in spec.
func NewUpdateFoodParams() UpdateFoodParams {

	return UpdateFoodParams{}
}

// UpdateFoodParams contains all the bound params for the update food operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateFood
type UpdateFoodParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Body *models.Food
	/*
	  Required: true
	  In: path
	*/
	FoodID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateFoodParams() beforehand.
func (o *UpdateFoodParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Food
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	}
	rFoodID, rhkFoodID, _ := route.Params.GetOK("food_id")
	if err := o.bindFoodID(rFoodID, rhkFoodID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFoodID binds and validates parameter FoodID from path.
func (o *UpdateFoodParams) bindFoodID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("food_id", "path", "int64", raw)
	}
	o.FoodID = value

	return nil
}
